import path from 'node:path'
import { fileURLToPath } from 'node:url'
import js from '@eslint/js'
import { FlatCompat } from '@eslint/eslintrc'
import { defineConfig, globalIgnores } from 'eslint/config'
import eslintConfigPrettier from 'eslint-config-prettier'
import globals from 'globals'
import tseslint from 'typescript-eslint'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const compat = new FlatCompat({ baseDirectory: __dirname })

export default defineConfig([
  // next-env.d.ts is auto-generated by Next.js and required to use a triple-slash reference.
  globalIgnores(['.next', 'out', 'playwright-report', 'test-results', 'next-env.d.ts']),
  js.configs.recommended,
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
      parserOptions: {
        // allowDefaultProject lets root-level tooling configs (this file included) get an
        // inferred program instead of erroring for not being part of tsconfig's `include`.
        // Only .js/.mjs config files need this — next.config.ts is already picked up by
        // tsconfig's `**/*.ts` include, so listing it here would conflict with that.
        projectService: {
          allowDefaultProject: ['*.config.{js,mjs}', 'scripts/*.js'],
        },
        tsconfigRootDir: __dirname,
      },
    },
  },
  // Prettier owns formatting; this must stay last so it can disable conflicting style rules.
  eslintConfigPrettier,
])
